[project]
name = "plasmapy-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nick Murphy", email = "namurphy@cfa.harvard.edu" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
plasmapy-calculator = "plasmapy_calculator:main"

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"
